### ISSUE TITLE
Using super in order decorator

### ISSUE THREAD

**Issue by kennyadsl** [magma-labs/solidus_payment_method_by_zone#2]
What about using super [here](https://github.com/magma-labs/solidus_payment_method_by_zone/blob/master/app/models/spree/order_decorator.rb#L5)? 

[The method in core already returns an `ActiveRecord::Relation`](https://github.com/solidusio/solidus/blob/1a4444a07875753e18fbc5b99d3e7bad41896ff5/core/app/models/spree/order.rb#L451) and I think you can just chain scopes to its return value, something like:

```ruby
def available_payment_methods
  @available_payment_methods ||= super
    .left_joins(:payment_method_zone)
    .where(spree_payment_method_zones: {zone_id: [nil] + Spree::Zone.for_address(ship_address).pluck(&:id)})
end
```

What do you think?

**Comment by jtapia** [comment]
@kennyadsl thanks, I'm currently testing this change and I'm getting 
```
super: no superclass method `available_payment_methods' for #<Spree::Order:0x00007fe8d8ff1ea0>
```
I'll continue checking this, any update I'll post here

**Comment by softr8** [comment]
thanks for the suggetsion @kennyadsl ! implemented [here](https://github.com/magma-labs/solidus_payment_method_by_zone/blob/master/app/decorators/models/solidus_payment_method_by_zone/spree/order_decorator.rb#L5)
